name: quick_alarm
description: App to setup quick alarms
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  android_alarm_manager: ^0.4.5+11
  flutter_ringtone_player: ^2.0.0
  shared_preferences: ^0.5.7+3
  rxdart: ^0.24.0
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_launcher_icons
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/app-icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
